name=DFRobot_ID809
version=1.0.0
author=DFRobot
maintainer=TangJie <jie.tang@dfrobot.com>
sentence=This capacitive fingerprint sensor supports fingerprint capture, image processing, fingerprint storage, fingerprint comparison and so on.
paragraph=This capacitive fingerprint sensor supports fingerprint capture, image processing, fingerprint storage, fingerprint comparison and so on.
category=Sensors
url=https://github.com/DFRobot/DFRobot_ID809
architectures=*